@startuml
scale 850 width
[*]-->managerWEB:访问web管理界面
Eureka-->redisDB:监控redisServer节点队列是否正常
AP --> Eureka :订阅
redisProxys -> Eureka : 注册
redisProxys --> redisDB

redisDB->x_pipeSvc:同步数据

state redisMonitor{
    managerWEB -> redisManager:管理
    redisManager-->redisDB:管理与部署redisServer

    state managerWEB{
    }
    state redisManager{
    }

}

state AP{
  APRedisClient1 --> redisProxys:redis协议
  APRedisClient2 --> redisProxys:redis协议
  APRedisClient3 --> redisProxys:redis协议
}

state Eureka{
    state eureka1{
        state redisFailOver1
    }
    state eureka2{
        state redisFailOver2
    }
    state eureka3{
        state redisFailOver3
    }
    Eureka -->redisManager:redisFailOver调用更新服务
  }

state redisProxys {

  state redisProxy1{

  }
  state redisProxy2{

  }
  state redisProxy3{

  }

}

state redisDB {

  [*] --> redis1 : hash访问
  [*] --> redis2 : hash访问
  [*] --> redis3 : hash访问

  state redis1 {
     master1 -> salve1 : sync
     salve1 --> master1 : switch
  }
  state redis2 {
       master2 -> salve2 : sync
       salve2 --> master2 : switch
    }
  state redis3 {
        master3 -> salve3 : sync
        salve3 --> master3 : switch
   }

}

state x_pipeSvc{
    [*]-->DB_interface
    [*]-->ES_interface
    [*]-->MQ_interface
    [*]-->HDFS_interface

}
@enduml